This is a quick notebook to show the contents of the tables in the database. The tables are:

- `commits`: the commits in the repository
- `diffs`: the file changes

In [5]:
import pandas as pd
import sqlite3

In [6]:
# read in the git_diff.db
con = sqlite3.connect("data/git_diff.db")
cur = con.cursor()

In [7]:
# read in the commits table
commits = pd.read_sql_query("SELECT * FROM commits", con)
commits.head()

,rowid,commit_hash,author,date,message,repo
0,1,692bba578efb5e305c9b116568e5aad75b3fdbb3,Mortada Mehyar <mortada@users.noreply.github.com>,Wed Apr 21 12:27:07 2021 +0800,DOC: add example for plotting asymmetrical err...,pandas-dev/pandas
1,2,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,Patrick Hoefler <61934744+phofl@users.noreply....,Wed Apr 21 01:23:07 2021 +0200,Add keyword sort to pivot_table (#40954),pandas-dev/pandas
2,3,eaaefd140289a5103679ac6748567f724c7be56a,attack68 <24256554+attack68@users.noreply.gith...,Wed Apr 21 01:21:22 2021 +0200,ENH: `Styler.highlight_quantile` method (#40926),pandas-dev/pandas
3,4,aab87997058f3c74ba70286620ebe792ee4ef169,attack68 <24256554+attack68@users.noreply.gith...,Wed Apr 21 01:01:03 2021 +0200,ENH: add `decimal` and `thousands` args to `St...,pandas-dev/pandas
4,5,9c43cd7675d96174051e470de1f45e2bf7c9ebdc,Simon Hawkins <simonjayhawkins@gmail.com>,Tue Apr 20 23:58:18 2021 +0100,[ArrowStringArray] Use utf8_upper and utf8_low...,pandas-dev/pandas

In [8]:
# read in the diff table
diff = pd.read_sql_query("SELECT * FROM diff", con)
diff.head()

,rowid,commit_hash,additions,deletions,filename,patch
0,1,692bba578efb5e305c9b116568e5aad75b3fdbb3,26,6,doc/source/user_guide/visualization.rst,"@@ -1458,25 +1458,23 @@ Horizontal and vertica..."
1,2,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,1,0,doc/source/whatsnew/v1.3.0.rst,"@@ -221,6 +221,7 @@ Other enhancements\n - :me..."
2,3,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,7,0,pandas/core/frame.py,"@@ -7781,6 +7781,11 @@ def pivot(self, index=N..."
3,4,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,5,1,pandas/core/reshape/pivot.py,"@@ -64,6 +64,7 @@ def pivot_table(\n dropn..."
4,5,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,22,0,pandas/tests/reshape/test_pivot.py,"@@ -2115,6 +2115,28 @@ def test_pivot_table_do..."

Here's what it looks like to perform a join on the two tables.

In [9]:
df = pd.merge(commits, diff, on='commit_hash')
df.head()

,rowid_x,commit_hash,author,date,message,repo,rowid_y,additions,deletions,filename,patch
0,1,692bba578efb5e305c9b116568e5aad75b3fdbb3,Mortada Mehyar <mortada@users.noreply.github.com>,Wed Apr 21 12:27:07 2021 +0800,DOC: add example for plotting asymmetrical err...,pandas-dev/pandas,1,26,6,doc/source/user_guide/visualization.rst,"@@ -1458,25 +1458,23 @@ Horizontal and vertica..."
1,2,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,Patrick Hoefler <61934744+phofl@users.noreply....,Wed Apr 21 01:23:07 2021 +0200,Add keyword sort to pivot_table (#40954),pandas-dev/pandas,2,1,0,doc/source/whatsnew/v1.3.0.rst,"@@ -221,6 +221,7 @@ Other enhancements\n - :me..."
2,2,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,Patrick Hoefler <61934744+phofl@users.noreply....,Wed Apr 21 01:23:07 2021 +0200,Add keyword sort to pivot_table (#40954),pandas-dev/pandas,3,7,0,pandas/core/frame.py,"@@ -7781,6 +7781,11 @@ def pivot(self, index=N..."
3,2,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,Patrick Hoefler <61934744+phofl@users.noreply....,Wed Apr 21 01:23:07 2021 +0200,Add keyword sort to pivot_table (#40954),pandas-dev/pandas,4,5,1,pandas/core/reshape/pivot.py,"@@ -64,6 +64,7 @@ def pivot_table(\n dropn..."
4,2,855696cde0ef5d80a7d4bd3f6a2940c5a2fecb3f,Patrick Hoefler <61934744+phofl@users.noreply....,Wed Apr 21 01:23:07 2021 +0200,Add keyword sort to pivot_table (#40954),pandas-dev/pandas,5,22,0,pandas/tests/reshape/test_pivot.py,"@@ -2115,6 +2115,28 @@ def test_pivot_table_do..."